# Generated by Django 4.2.4 on 2023-08-18 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/products/'),
            preserve_default=False,
        ),
    ]
